'use client'
import {useCallback,useEffect,useRef,useState} from 'react'
type Plan={key:string;label:string;priceId:string;amountCents:number;currency:string;interval:string;taxBehavior:string}
type State={paid:boolean;configured:boolean;taxMode:string;portalConfigured:boolean;subscription:null|{status:string;planKey:string|null;paidThrough:string|null;cancelAtPeriodEnd:boolean;checkedAt:string|null};attempts:{id:string;planKey:string;amountCents:number;interval:string;status:string;sessionId:string|null;error:string|null}[]}
const field='w-full rounded border border-gray-300 p-2',button='rounded bg-blue-700 px-4 py-2 text-white disabled:opacity-50'
export default function Billing(){
 const [data,setData]=useState<State|null>(null),[plans,setPlans]=useState<Plan[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState(''),[confirmed,setConfirmed]=useState(false),[reference,setReference]=useState('');const retry=useRef<{input:string;key:string}|null>(null)
 const load=useCallback(async()=>{const response=await fetch('/api/software-billing',{cache:'no-store'}),value=await response.json();if(!response.ok)throw Error(value.error||'Billing could not be loaded');setData(value)},[])
 useEffect(()=>{load().catch(e=>setError(e.message));const value=new URLSearchParams(window.location.search).get('checkout');if(value?.startsWith('cs_'))setReference(value)},[load])
 async function act(input:Record<string,unknown>,redirect=false){const fingerprint=JSON.stringify(input);if(retry.current?.input!==fingerprint)retry.current={input:fingerprint,key:crypto.randomUUID()};setBusy(true);setError('');try{const response=await fetch('/api/software-billing',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':retry.current.key},body:JSON.stringify(input)}),value=await response.json();if(response.status<500)retry.current=null;if(!response.ok)throw Error(value.error||'Billing request failed');if(input.action==='PRICES'){setPlans(value.plans);setConfirmed(false)}await load();if(redirect&&value.url)window.location.assign(value.url)}catch(e){setError(e instanceof Error?e.message:'Billing request failed')}finally{setBusy(false)}}
 const plan=plans.find(p=>p.key===selected)
 return <main className="mx-auto max-w-4xl space-y-6 p-6"><h1 className="text-3xl font-bold">Software subscription</h1><p>Manage this company’s HomeServices software plan and billing records.</p>{error&&<p role="alert" className="rounded bg-red-50 p-3 text-red-800">{error}</p>}
 {!data?<button className={button} onClick={()=>load().catch(e=>setError(e.message))}>Reload billing</button>:<>
 <section className="space-y-3 rounded border bg-white p-5"><h2 className="text-xl font-semibold">Current subscription</h2><p>{data.subscription?.status||'UNSUBSCRIBED'} · {data.subscription?.planKey||'No paid plan'}</p><p>{data.paid?'Verified paid period is current.':'A current paid period has not been verified.'}</p>{data.subscription?.paidThrough&&<p>Verified through: {new Date(data.subscription.paidThrough).toLocaleString()}</p>}{data.subscription?.checkedAt&&<p>Last provider check: {new Date(data.subscription.checkedAt).toLocaleString()}</p>}{data.subscription?.cancelAtPeriodEnd&&<p>Cancellation is scheduled for the end of the current period.</p>}<div className="flex flex-wrap gap-2"><button className={button} disabled={busy||!data.configured} onClick={()=>act({action:'REFRESH'})}>Refresh provider status</button><button className={button} disabled={busy||!data.configured||!data.portalConfigured||!data.subscription} onClick={()=>act({action:'PORTAL'},true)}>Manage subscription & invoices</button></div><p className="text-sm">The provider portal supports configured plan changes, payment methods, invoice downloads and cancellation. Returning from checkout does not prove payment.</p></section>
 <section className="space-y-4 rounded border bg-white p-5"><h2 className="text-xl font-semibold">Choose a software plan</h2>{!data.configured&&<p>Software billing is not configured. An operator must configure the platform’s Stripe account, plan prices and tax settings.</p>}<button className={button} disabled={busy||!data.configured} onClick={()=>act({action:'PRICES'})}>Load current plan prices</button>{plans.length>0&&<><label className="block">Plan<select className={field} value={selected} onChange={e=>{setSelected(e.target.value);setConfirmed(false)}}><option value="">Choose a plan</option>{plans.map(p=><option key={p.key} value={p.key}>{p.label} · ${(p.amountCents/100).toFixed(2)} USD / {p.interval}</option>)}</select></label>{plan&&<p>Recurring price: ${(plan.amountCents/100).toFixed(2)} USD per {plan.interval}. {data.taxMode==='automatic'?'Applicable taxes are calculated at checkout.':'Tax configuration: '+data.taxMode+'.'} The hosted checkout shows the final recurring terms.</p>}<label className="block"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> I have authority to purchase this recurring software plan and have reviewed its price and interval.</label><button className={button} disabled={busy||!confirmed||!plan} onClick={()=>act({action:'CHECKOUT',planKey:plan!.key,expectedAmountCents:plan!.amountCents,expectedInterval:plan!.interval,confirmed:true},true)}>Continue to subscription checkout</button></>}</section>
 <section className="space-y-3 rounded border bg-white p-5"><h2 className="text-xl font-semibold">Saved checkouts</h2><label className="block">Provider checkout reference<input className={field} value={reference} onChange={e=>setReference(e.target.value)} placeholder="cs_…"/></label><button className={button} disabled={busy||!reference||!data.configured} onClick={()=>act({action:'RECONCILE',sessionId:reference})}>Reconcile checkout reference</button>{data.attempts.length===0&&<p>No software checkout has been started.</p>}{data.attempts.map(a=><article className="space-y-2 border-t py-3" key={a.id}><h3 className="font-semibold">{a.planKey} · {a.status}</h3><p>${(a.amountCents/100).toFixed(2)} USD / {a.interval}</p>{a.error&&<p>{a.error}</p>}{a.sessionId&&<p className="break-all">{a.sessionId}</p>}<div className="flex flex-wrap gap-2">{['PENDING','RUNNING','UNKNOWN','OPEN'].includes(a.status)&&<button className={button} disabled={busy||!data.configured} onClick={()=>act({action:'RESUME',id:a.id},true)}>Open or recover saved checkout</button>}{a.sessionId&&<button className={button} disabled={busy||!data.configured} onClick={()=>act({action:'RECONCILE',sessionId:a.sessionId})}>Check provider receipt</button>}{a.sessionId&&a.status==='OPEN'&&<button className={button} disabled={busy||!data.configured} onClick={()=>{if(window.confirm('Expire this unpaid checkout at the provider?'))act({action:'EXPIRE',sessionId:a.sessionId,confirmed:true})}}>Expire unpaid checkout</button>}</div></article>)}<p className="text-sm">Unknown requests remain reserved. Recover the same request within 23 hours; older uncertain requests need a provider reference. Do not create a replacement until the original is reconciled.</p></section>
 </>}
 </main>
}
