'use client'
import {useEffect,useState} from 'react'
import Link from 'next/link'
import AIFormAssistant from '@/components/AIFormAssistant'
import {useWorkflowFetch} from '@/hooks/useWorkflowFetch'
export default function IntakeInbox(){
  const [data,setData]=useState<any>(null),[lookup,setLookup]=useState<any>(null),[selected,setSelected]=useState<any>(null),[form,setForm]=useState<Record<string,any>>({}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('')
  const mutate=useWorkflowFetch(),change=(k:string,v:any)=>setForm(p=>({...p,[k]:v}))
  async function load(){const values=await Promise.all(['/api/operations/intake','/api/operations/lookups'].map(async p=>{const r=await fetch(p),d=await r.json();if(!r.ok)throw Error(d.error);return d}));setData(values[0]);setLookup(values[1])}
  useEffect(()=>{void load().catch(e=>setError(e.message))},[])
  async function send(body:any){setBusy(true);setError('');setNotice('');try{const r=await mutate('/api/operations/intake',body),d=await r.json();if(!r.ok)throw Error(d.error);if(d.bookingId)setNotice('Booking request created. Assign a technician and confirm it in Bookings.');setSelected(null);await load()}catch(e){setError(e instanceof Error?e.message:'Request failed')}finally{setBusy(false)}}
  function choose(row:any){setSelected(row);setForm({...row.data,title:row.title,notes:`${row.data.notes}\nRequested address: ${row.data.address||'Unknown'}\nPreferred time: ${row.data.preferredTime||'Not provided'}`,customerId:'',createCustomer:false,reviewed:false})}
  const field=(label:string,key:string,type='text',required=false)=><label className="block">{label}<input type={type} className="input w-full" value={form[key]||''} required={required} onChange={e=>change(key,e.target.value)}/></label>
  return <main className="max-w-6xl space-y-5"><Link href="/dashboard/operations">← Operations</Link><h1 className="text-2xl font-bold">Customer intake</h1><p>Review website, SMS and telephone requests, then create an editable booking request.</p>
    {error&&<p role="alert" className="bg-red-50 p-3 text-red-800">{error}</p>}{notice&&<p role="status" className="bg-green-50 p-3">{notice} <Link className="underline" href="/dashboard/operations/bookings">Open bookings</Link></p>}
    {data&&<section className="card p-4 space-y-2"><p>Public booking page: {data.published?'Enabled':'Disabled'}</p>{data.published&&<a className="text-primary-700 underline break-all" target="_blank" rel="noreferrer" href={data.publicUrl}>{data.publicUrl}</a>}{data.canPublish&&<div><button className="btn btn-secondary" disabled={busy} onClick={()=>void send({action:'publish',enabled:!data.published})}>{data.published?'Disable':'Enable'} online booking</button></div>}</section>}
    {selected&&<form className="card p-5 space-y-4" onSubmit={e=>{e.preventDefault();void send({...form,action:'convert',id:selected.id,version:selected.version,startAt:new Date(form.startAt).toISOString(),endAt:new Date(form.endAt).toISOString()})}}>
      <h2 className="font-semibold">Review request</h2><AIFormAssistant key={selected.id} form="operations:bookings" values={form} customerId={form.customerId} disabled={busy} onApply={patch=>setForm(p=>({...p,...patch}))}/>
      <div className="grid md:grid-cols-2 gap-3"><label>Customer<select className="select w-full" value={form.customerId||''} onChange={e=>{change('customerId',e.target.value);change('propertyId','');change('createCustomer',false)}}><option value="">Select an existing customer</option>{lookup?.customers.map((c:any)=><option key={c.id} value={c.id}>{c.firstName} {c.lastName}</option>)}</select></label><label>Service<select className="select w-full" required value={form.serviceTypeId||''} onChange={e=>change('serviceTypeId',e.target.value)}><option value="">Select service</option>{lookup?.serviceTypes.map((s:any)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>
      {!form.customerId&&<><label><input type="checkbox" checked={form.createCustomer===true} onChange={e=>change('createCustomer',e.target.checked)}/> Create a new customer after reviewing contact details</label>{form.createCustomer&&<>{field('First name','firstName','text',true)}{field('Last name','lastName','text',true)}{field('Email','email','email')}{field('Phone with country code','phone','tel')}</>}</>}
      {form.customerId&&<label>Property<select className="select w-full" value={form.propertyId||''} onChange={e=>change('propertyId',e.target.value)}><option value="">No property selected</option>{lookup?.properties.filter((p:any)=>p.customerId===form.customerId).map((p:any)=><option key={p.id} value={p.id}>{p.address}</option>)}</select></label>}
      {field('Title','title','text',true)}{field('Requested start (your local time)','startAt','datetime-local',true)}{field('Requested end (your local time)','endAt','datetime-local',true)}</div>
      <label className="block">Request notes<textarea className="input w-full" rows={5} required value={form.notes||''} onChange={e=>change('notes',e.target.value)}/></label>
      <label className="block"><input type="checkbox" required checked={form.reviewed===true} onChange={e=>change('reviewed',e.target.checked)}/> I reviewed the customer, service and requested appointment.</label>
      <div className="flex gap-3"><button className="btn btn-primary" disabled={busy}>Create booking request</button><button type="button" className="btn btn-secondary" onClick={()=>setSelected(null)}>Close</button></div>
    </form>}
    <div className="space-y-3">{data?.rows.map((r:any)=><article className="card p-4 space-y-2" key={r.id}><div className="flex justify-between gap-3"><h2 className="font-semibold">{r.title}</h2><span>{r.status}</span></div><p className="whitespace-pre-wrap">{r.data.notes}</p><p className="text-sm">{r.data.email} {r.data.phone} · {new Date(r.createdAt).toLocaleString()}</p>{r.status==='NEW'&&<div className="flex gap-3"><button className="btn btn-primary" disabled={busy} onClick={()=>choose(r)}>Review & draft booking</button><button className="btn btn-secondary" disabled={busy} onClick={()=>void send({action:'archive',id:r.id,version:r.version})}>Archive</button></div>}{r.data.bookingId&&<Link className="underline" href="/dashboard/operations/bookings">Open bookings</Link>}</article>)}{data&&!data.rows.length&&<p>No incoming requests yet. Enable your booking page or configure Twilio in Integrations.</p>}</div>
  </main>
}
